### ISSUE TITLE
Sync with iCloud - Create new File - old app name

### ISSUE THREAD

**Issue by andrev68** [holtwick/onepile#97] opened 2019-07-14 21:09 UTC
**Describe the bug**
Creating a new container is visible in the Files App under the old name "Collect"

**To Reproduce**
1. Create new Container
2. Open iCloud Drive
3. Check App/Folder Name
4. Collect

**Expected behavior**
OnePile

**Smartphone (please complete the following information):**
 - Version 1070

**Comment by holtwick** [comment] 2019-07-15 19:46
See also #98

**Comment by holtwick** [comment] 2019-07-15 21:44
@andrev68 I cannot reproduce this error. When I create a new file on iOS without adding a file ending e.g. "Test", then `.onepile` is added to the file name. The folder is also OnePile. If this still happens, could you provide a video? Thanks.

**Comment by holtwick** [comment] 2019-07-18 16:55
I think this should be solved now and is only when transitioning from a previous Collect installation. #79 The name "Collect" has been replaced by "OnePile" in all sources as far as making sense. Closing issue.

**Closed by holtwick** 2019-07-18 16:55 UTC
Labels: bug, bug_report, database, ios
